///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#include <wx/artprov.h>
#include <wx/bitmap.h>
#include <wx/bmpbndl.h>
#include <wx/event.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/menu.h>
#include <wx/sizer.h>
#include <wx/statbmp.h>
#include <wx/statbox.h>
#include <wx/valgen.h>
#include <wx/valtext.h>
#include <wx/window.h>

#include "custom_ctrls/split_button.h"
#include "images.h"

#include "commonctrls.h"

#include <wx/animate.h>

#include <wx/mstream.h>  // memory stream classes
#include <wx/zstream.h>  // zlib stream classes

#include <memory>  // for std::make_unique

// Convert a data array into a wxImage
#ifdef __cpp_inline_variables
inline wxImage wxueImage(const unsigned char* data, size_t size_data)
#else
static wxImage wxueImage(const unsigned char* data, size_t size_data)
#endif
{
    wxMemoryInputStream strm(data, size_data);
    wxImage image;
    image.LoadFile(strm);
    return image;
};

// Convert a data array into a wxAnimation
#ifdef __cpp_inline_variables
inline void wxueAnimation(const unsigned char* data, size_t size_data, wxAnimation& animation)
#else
static void wxueAnimation(const unsigned char* data, size_t size_data, wxAnimation& animation)
#endif
{
    wxMemoryInputStream strm(data, size_data);
    animation.Load(strm);
};

namespace wxue_img
{
    extern const unsigned char clr_hourglass_gif[2017];  // art/clr_hourglass.gif
    extern const unsigned char face_smile_webp[2148];  // art/../art/face-smile.webp
}

bool CommonCtrls::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
    {
        return false;
    }
    if (!wxImage::FindHandler(wxBITMAP_TYPE_GIF))
        wxImage::AddHandler(new wxGIFHandler);
    if (!wxImage::FindHandler(wxBITMAP_TYPE_PNG))
        wxImage::AddHandler(new wxPNGHandler);
    if (!wxImage::FindHandler(wxBITMAP_TYPE_WEBP))
        wxImage::AddHandler(new wxWEBPHandler);

    auto* parent_sizer = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer6 = new wxBoxSizer(wxVERTICAL);

    m_infoBar = new wxInfoBar(this);
    m_infoBar->SetShowHideEffects(wxSHOW_EFFECT_EXPAND, wxSHOW_EFFECT_NONE);
    m_infoBar->SetEffectDuration(500);
    box_sizer6->Add(m_infoBar, wxSizerFlags().Expand().Border(wxALL));

    parent_sizer->Add(box_sizer6, wxSizerFlags().Expand().Border(wxALL));

    auto* box_sizer = new wxBoxSizer(wxHORIZONTAL);

    m_staticText = new wxStaticText(this, wxID_ANY, "Text:");
    box_sizer->Add(m_staticText, wxSizerFlags().Center().Border(wxLEFT|wxTOP|wxBOTTOM, wxSizerFlags::GetDefaultBorder()));

    m_textCtrl = new wxTextCtrl(this, TXT_CTRL, "Text \"ctrl\"", wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    {
        wxArrayString tmp_array;
        tmp_array.Add("foo");
        tmp_array.Add("bar");
        m_textCtrl->AutoComplete(tmp_array);
    }
    m_textCtrl->SetValidator(wxTextValidator(wxFILTER_NONE, &m_textCtrlValidate));
    m_textCtrl->SetToolTip("Auto-complete contains \"foo\" and \"bar\"");
    box_sizer->Add(m_textCtrl, wxSizerFlags().Border(wxALL));

    m_staticText2 = new wxStaticText(this, wxID_ANY, "More text:");
    box_sizer->Add(m_staticText2, wxSizerFlags().Center().Border(wxLEFT|wxTOP|wxBOTTOM, wxSizerFlags::GetDefaultBorder()));

    m_textCtrl2 = new wxTextCtrl(this, wxID_ANY, "Another ctrl");
    box_sizer->Add(m_textCtrl2, wxSizerFlags().Border(wxALL));

    m_checkBox = new wxCheckBox(this, wxID_ANY, "2-state Checkbox");
    box_sizer->Add(m_checkBox, wxSizerFlags().Center().Border(wxALL));

    parent_sizer->Add(box_sizer, wxSizerFlags().Expand().Border(wxALL));

    auto* box_sizer2 = new wxBoxSizer(wxHORIZONTAL);

    m_btn = new wxButton(this, wxID_ANY, "First btn");
    box_sizer2->Add(m_btn, wxSizerFlags().Border(wxALL));

    auto* btn2 = new wxButton(this, wxID_ANY, "Popup");
    box_sizer2->Add(btn2, wxSizerFlags().Border(wxALL));

    m_radioBtn = new wxRadioButton(this, wxID_ANY, "First radio", wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    box_sizer2->Add(m_radioBtn, wxSizerFlags().Center().Border(wxALL));

    m_radioBtn2 = new wxRadioButton(this, wxID_ANY, "Second radio");
    box_sizer2->Add(m_radioBtn2, wxSizerFlags().Center().Border(wxALL));

    m_checkBox2 = new wxCheckBox(this, wxID_ANY, "Checkbox");
    box_sizer2->Add(m_checkBox2, wxSizerFlags().Center().Border(wxALL));

    parent_sizer->Add(box_sizer2, wxSizerFlags().Expand().Border(wxALL));

    auto* static_box = new wxStaticBoxSizer(wxVERTICAL, this, "Combos and Choices");

    auto* box_sizer3 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_box_sizer2 = new wxStaticBoxSizer(wxVERTICAL, static_box->GetStaticBox(), "Combo");

    m_staticText3 = new wxStaticText(static_box_sizer2->GetStaticBox(), wxID_ANY, "Unsorted");
    static_box_sizer2->Add(m_staticText3, wxSizerFlags().Border(wxALL));

    m_comboBox = new wxComboBox(static_box_sizer2->GetStaticBox(), wxID_ANY);
    m_comboBox->Append("item #1");
    m_comboBox->Append("item #2");
    m_comboBox->Append("item #0");
    m_comboBox->SetStringSelection("item #2");
    m_comboBox->SetToolTip("Item #0 should be selected by default");
    static_box_sizer2->Add(m_comboBox, wxSizerFlags().Expand().Border(wxALL));

    m_staticText4 = new wxStaticText(static_box_sizer2->GetStaticBox(), wxID_ANY, "Sorted");
    static_box_sizer2->Add(m_staticText4, wxSizerFlags().Border(wxALL));

    m_comboBox2 = new wxComboBox(static_box_sizer2->GetStaticBox(), wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        0, nullptr, wxCB_SORT);
    m_comboBox2->Append("item #1");
    m_comboBox2->Append("item #2");
    m_comboBox2->Append("item #0");
    m_comboBox2->SetStringSelection("item #2");
    m_comboBox2->SetToolTip("Item #2 should be selected by default");
    static_box_sizer2->Add(m_comboBox2, wxSizerFlags().Border(wxALL));

    box_sizer3->Add(static_box_sizer2, wxSizerFlags().Expand().Border(wxALL));

    auto* static_box_sizer3 = new wxStaticBoxSizer(wxVERTICAL, static_box->GetStaticBox(), "Choice");

    m_staticText5 = new wxStaticText(static_box_sizer3->GetStaticBox(), wxID_ANY, "Unsorted");
    static_box_sizer3->Add(m_staticText5, wxSizerFlags().Border(wxALL));

    m_choice = new wxChoice(static_box_sizer3->GetStaticBox(), wxID_ANY);
    m_choice->Append("item #1");
    m_choice->Append("item #2");
    m_choice->Append("item #0");
    m_choice->SetSelection(2);
    m_choice->SetToolTip("Item #0 should be selected by default");
    static_box_sizer3->Add(m_choice, wxSizerFlags().Border(wxALL));

    m_staticText6 = new wxStaticText(static_box_sizer3->GetStaticBox(), wxID_ANY, "Sorted");
    static_box_sizer3->Add(m_staticText6, wxSizerFlags().Border(wxALL));

    m_choice2 = new wxChoice(static_box_sizer3->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize,
        0, nullptr, wxCB_SORT);
    m_choice2->Append("item #1");
    m_choice2->Append("item #2");
    m_choice2->Append("item #0");
    m_choice2->SetSelection(2);
    m_choice2->SetToolTip("Item #2 should be selected by default");
    static_box_sizer3->Add(m_choice2, wxSizerFlags().Border(wxALL));

    box_sizer3->Add(static_box_sizer3, wxSizerFlags().Expand().Border(wxALL));

    auto* static_box_sizer4 = new wxStaticBoxSizer(wxVERTICAL, static_box->GetStaticBox(), "List");

    m_staticText7 = new wxStaticText(static_box_sizer4->GetStaticBox(), wxID_ANY, "Unsorted");
    static_box_sizer4->Add(m_staticText7, wxSizerFlags().Border(wxALL));

    m_listbox = new wxListBox(static_box_sizer4->GetStaticBox(), wxID_ANY);
    m_listbox->Append("item #1");
    m_listbox->Append("item #2");
    m_listbox->Append("item #0");
    static_box_sizer4->Add(m_listbox, wxSizerFlags().Border(wxALL));

    m_staticText8 = new wxStaticText(static_box_sizer4->GetStaticBox(), wxID_ANY, "Sorted");
    static_box_sizer4->Add(m_staticText8, wxSizerFlags().Border(wxALL));

    m_listBox2 = new wxListBox(static_box_sizer4->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, nullptr,
        wxLB_SINGLE|wxLB_SORT);
    m_listBox2->Append("item #1");
    m_listBox2->Append("item #2");
    m_listBox2->Append("item #0");
    static_box_sizer4->Add(m_listBox2, wxSizerFlags().Border(wxALL));

    box_sizer3->Add(static_box_sizer4, wxSizerFlags().Expand().Border(wxALL));

    auto* static_box_sizer5 = new wxStaticBoxSizer(wxVERTICAL, static_box->GetStaticBox(), "Checked");

    m_staticText9 = new wxStaticText(static_box_sizer5->GetStaticBox(), wxID_ANY, "Unsorted");
    static_box_sizer5->Add(m_staticText9, wxSizerFlags().Border(wxALL));

    m_checkList = new wxCheckListBox(static_box_sizer5->GetStaticBox(), wxID_ANY);
    m_checkList->Append("item #1");
    m_checkList->Append("item #2");
    m_checkList->Append("item #0");
    static_box_sizer5->Add(m_checkList, wxSizerFlags().Border(wxALL));

    m_staticText10 = new wxStaticText(static_box_sizer5->GetStaticBox(), wxID_ANY, "Sorted");
    static_box_sizer5->Add(m_staticText10, wxSizerFlags().Border(wxALL));

    m_checkList2 = new wxCheckListBox(static_box_sizer5->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, nullptr,
        wxLB_SINGLE|wxLB_SORT);
    m_checkList2->Append("item #1");
    m_checkList2->Append("item #2");
    m_checkList2->Append("item #0");
    static_box_sizer5->Add(m_checkList2, wxSizerFlags().Border(wxALL));

    box_sizer3->Add(static_box_sizer5, wxSizerFlags().Expand().Border(wxALL));

    static_box->Add(box_sizer3, wxSizerFlags().Expand().Border(wxALL));

    parent_sizer->Add(static_box, wxSizerFlags().Expand().Border(wxALL));

    auto* flex_grid_sizer = new wxFlexGridSizer(4, 0, 0);

    m_staticText11 = new wxStaticText(this, wxID_ANY,
        "On Windows 10, the items may be be clipped unless they have a trailing space.");
    m_staticText11->Wrap(200);
    flex_grid_sizer->Add(m_staticText11, wxSizerFlags().Border(wxALL));

    wxString radioBox_choices[] = {
        "Button zero ",
        "Button one ",
        "Button two "
    };
    // Trailing spaces added to avoid clipping
    m_radioBox = new wxRadioBox(this, wxID_ANY, "Radio Box", wxDefaultPosition, wxDefaultSize, 3, radioBox_choices, 0,
        wxRA_SPECIFY_ROWS);
    m_radioBox->SetSelection(1);
    m_radioBox->SetValidator(wxGenericValidator(&m_valRadio));
    flex_grid_sizer->Add(m_radioBox, wxSizerFlags().Border(wxALL));

    auto* box_sizer_2 = new wxBoxSizer(wxVERTICAL);

    auto* bmp = new wxStaticBitmap(this, wxID_ANY, wxue_img::bundle_face_smile_svg(64, 64));
    box_sizer_2->Add(bmp, wxSizerFlags().Border(wxALL));

    m_staticText_2 = new wxStaticText(this, wxID_ANY, "SVG image");
    box_sizer_2->Add(m_staticText_2, wxSizerFlags().Border(wxALL));

    flex_grid_sizer->Add(box_sizer_2, wxSizerFlags().Border(wxALL));

    auto* box_sizer4 = new wxBoxSizer(wxVERTICAL);

    auto* bmp3 = new wxStaticBitmap(this, wxID_ANY, wxBitmapBundle::FromBitmap(wxueImage(wxue_img::face_smile_webp, sizeof(wxue_img::face_smile_webp))));
    box_sizer4->Add(bmp3, wxSizerFlags().Border(wxALL));

    m_staticText14 = new wxStaticText(this, wxID_ANY, "WEBP image");
    box_sizer4->Add(m_staticText14, wxSizerFlags().Border(wxALL));

    flex_grid_sizer->Add(box_sizer4, wxSizerFlags().Border(wxALL));

    m_checkPlayAnimation = new wxCheckBox(this, wxID_ANY, "Play Animation");
    auto* static_box_2 = new wxStaticBoxSizer(new wxStaticBox(this, wxID_ANY, m_checkPlayAnimation), wxVERTICAL);

    m_toggleBtn = new wxToggleButton(static_box_2->GetStaticBox(), wxID_ANY, "Play Animation", wxDefaultPosition,
        wxDefaultSize, wxBU_EXACTFIT);
    static_box_2->Add(m_toggleBtn, wxSizerFlags().Border(wxALL));

    m_animation_ctrl = new wxAnimationCtrl(static_box_2->GetStaticBox(), wxID_ANY, wxNullAnimation, wxDefaultPosition,
        wxDefaultSize, wxAC_DEFAULT_STYLE);
    m_animation_ctrl->SetInactiveBitmap(wxue_img::bundle_disabled_png());
    {
        auto animate = m_animation_ctrl->CreateAnimation();
        wxueAnimation(wxue_img::clr_hourglass_gif, sizeof(wxue_img::clr_hourglass_gif), animate);
        m_animation_ctrl->SetAnimation(animate);
    }
    static_box_2->Add(m_animation_ctrl, wxSizerFlags().Border(wxALL));

    flex_grid_sizer->Add(static_box_2, wxSizerFlags().Border(wxALL));

    m_bmpComboBox = new wxBitmapComboBox(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        0, nullptr, wxCB_READONLY);
    flex_grid_sizer->Add(m_bmpComboBox, wxSizerFlags().Border(wxALL));

    m_split_button = new wxue_ctrl::SplitButton(this, wxID_ANY, "Play");
    {
        const int ID_PLAY { 100 };
        const int ID_STOP { 101 };
        m_split_button->GetMenu().Append(ID_PLAY, "Play");
        m_split_button->GetMenu().Append(ID_STOP, "Stop");

        m_split_button->Bind(wxEVT_MENU,
            [this](wxCommandEvent&)
            {
                m_animation_ctrl->Play();
                m_checkPlayAnimation->SetValue(true);
            }, ID_PLAY);

        m_split_button->Bind(wxEVT_MENU,
            [this](wxCommandEvent&)
            {
                m_animation_ctrl->Stop();
                m_checkPlayAnimation->SetValue(false);
            }, ID_STOP);

        m_split_button->Bind(wxEVT_BUTTON,
            [this](wxCommandEvent&)
            {
                m_animation_ctrl->Play();
                m_checkPlayAnimation->SetValue(true);
            } );
    }
    flex_grid_sizer->Add(m_split_button, wxSizerFlags().DoubleBorder(wxALL));

    flex_grid_sizer->AddSpacer(0);

    m_edit_listbox = new wxEditableListBox(this, wxID_ANY, "My Editable ListBox", wxDefaultPosition, wxDefaultSize,
        wxEL_ALLOW_NEW|wxEL_ALLOW_EDIT|wxEL_ALLOW_DELETE);
    {
        wxArrayString tmp_array;
        tmp_array.push_back(wxString::FromUTF8("item #1"));
        tmp_array.push_back(wxString::FromUTF8("item #2"));
        tmp_array.push_back(wxString::FromUTF8("item #3"));
        m_edit_listbox->SetStrings(tmp_array);
    }
    flex_grid_sizer->Add(m_edit_listbox, wxSizerFlags().Border(wxALL));

    parent_sizer->Add(flex_grid_sizer, wxSizerFlags().Expand().Border(wxALL));

    auto* box_sizer5 = new wxBoxSizer(wxHORIZONTAL);

    m_staticText12 = new wxStaticText(this, wxID_ANY, "Slider:");
    box_sizer5->Add(m_staticText12, wxSizerFlags().Center().Border(wxLEFT|wxTOP|wxBOTTOM, wxSizerFlags::GetDefaultBorder()));

    m_slider = new wxSlider(this, wxID_ANY, 50, 0, 100);
    m_slider->SetValue(50);
    box_sizer5->Add(m_slider, wxSizerFlags().Border(wxALL));

    m_staticText13 = new wxStaticText(this, wxID_ANY, "Gauge:");
    box_sizer5->Add(m_staticText13, wxSizerFlags().Center().Border(wxLEFT|wxTOP|wxBOTTOM, wxSizerFlags::GetDefaultBorder()));

    m_gauge = new wxGauge(this, wxID_ANY, 100);
    m_gauge->SetValue(0);
    box_sizer5->Add(m_gauge, wxSizerFlags().Center().Border(wxALL));

    auto* bmp2 = new wxStaticBitmap(this, wxID_ANY, wxArtProvider::GetBitmapBundle(wxART_GO_HOME, wxART_OTHER));
    box_sizer5->Add(bmp2, wxSizerFlags().Border(wxALL));

    parent_sizer->Add(box_sizer5, wxSizerFlags().Expand().Border(wxALL));

    auto* stdBtn = CreateStdDialogButtonSizer(wxOK|wxCANCEL|wxHELP);
    parent_sizer->Add(CreateSeparatedSizer(stdBtn), wxSizerFlags().Expand().Border(wxALL));

    if (pos != wxDefaultPosition)
    {
        SetPosition(FromDIP(pos));
    }
    if (size == wxDefaultSize)
    {
        SetSizerAndFit(parent_sizer);
    }
    else
    {
        SetSizer(parent_sizer);
        if (size.x == wxDefaultCoord || size.y == wxDefaultCoord)
        {
            Fit();
        }
        SetSize(FromDIP(size));
        Layout();
    }
    Centre(wxBOTH);

    // Event handlers
    btn2->Bind(wxEVT_BUTTON, &CommonCtrls::OnPopupBtn, this);
    m_btn->Bind(wxEVT_BUTTON,
        [this](wxCommandEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_BUTTON event");
            Fit();
        });
    m_checkBox2->Bind(wxEVT_CHECKBOX, &CommonCtrls::OnCheckBox, this);
    m_checkBox->Bind(wxEVT_CHECKBOX,
        [this](wxCommandEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_CHECKBOX event");
            Fit();
                    
        });
    m_checkPlayAnimation->Bind(wxEVT_CHECKBOX,
        [this](wxCommandEvent&)
        {
            if (m_checkPlayAnimation->GetValue())
            {
                m_animation_ctrl->Play();
            }
            else
            { 
                m_animation_ctrl->Stop();
            }
                    
        });
    m_checkList->Bind(wxEVT_CHECKLISTBOX, &CommonCtrls::OnListChecked, this);
    m_choice2->Bind(wxEVT_CHOICE, &CommonCtrls::OnChoice, this);
    m_choice->Bind(wxEVT_CHOICE,
        [this](wxCommandEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_CHOICE event");
            Fit();
        });
    m_comboBox->Bind(wxEVT_COMBOBOX,
        [this](wxCommandEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_COMBOBOX event");
            Fit();
        });
    m_comboBox2->Bind(wxEVT_COMBOBOX,
        [this](wxCommandEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_COMBOBOX event");
            Fit();
        });
    m_comboBox2->Bind(wxEVT_COMBOBOX_CLOSEUP,
        [this](wxCommandEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_COMBOBOX_CLOSEUP event");
            Fit();
        });
    Bind(wxEVT_CONTEXT_MENU, &CommonCtrls::OnContextMenu, this);
    Bind(wxEVT_INIT_DIALOG, &CommonCtrls::OnInit, this);
    m_listBox2->Bind(wxEVT_LISTBOX, &CommonCtrls::OnListBox, this);
    m_listbox->Bind(wxEVT_LISTBOX, &CommonCtrls::OnListBox, this);
    m_edit_listbox->Bind(wxEVT_LIST_BEGIN_DRAG,
        [this](wxListEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_LIST_BEGIN_DRAG event");
            Fit();
        });
    m_radioBox->Bind(wxEVT_RADIOBOX, &CommonCtrls::OnRadioBox, this);
    m_radioBtn2->Bind(wxEVT_RADIOBUTTON, &CommonCtrls::OnRadio, this);
    m_radioBtn->Bind(wxEVT_RADIOBUTTON,
        [this](wxCommandEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_RADIOBUTTON event");
            Fit();
        });
    m_slider->Bind(wxEVT_SLIDER, &CommonCtrls::OnSlider, this);
    m_textCtrl->Bind(wxEVT_TEXT_ENTER,
        [this](wxCommandEvent&)
        {
            m_infoBar->ShowMessage("wxEVT_TEXT_ENTER event");
            Fit();
        });
    m_toggleBtn->Bind(wxEVT_TOGGLEBUTTON,
        [this](wxCommandEvent&)
        {
            if (m_toggleBtn->GetValue())
            {
                m_animation_ctrl->Play();
                m_checkPlayAnimation->SetValue(true);
            }
            else
            { 
                m_animation_ctrl->Stop();
                m_checkPlayAnimation->SetValue(false);
            }
                    
            m_infoBar->ShowMessage("wxEVT_TOGGLEBUTTON event");
            Fit();
        });

// Unimplemented Event handler functions
// Copy any of the following and paste them below the comment block, or to your inherited class.

/*
void CommonCtrls::OnContextMenu(wxContextMenuEvent& event)
{
    event.Skip();
}

*/

    return true;
}
void CommonCtrls::OnContextMenu(wxContextMenuEvent& event)
{
    wxMenu ctx_menu;
    auto* p_ctx_menu = &ctx_menu;  // convenience variable for the auto-generated code
    auto* menu_item = new wxMenuItem(p_ctx_menu, wxID_ANY, "Play Animation");
    p_ctx_menu->Append(menu_item);
    auto* menu_item_2 = new wxMenuItem(p_ctx_menu, wxID_ANY, "Stop Animation");
    p_ctx_menu->Append(menu_item_2);
    p_ctx_menu->AppendSeparator();
    auto* menu_item_3 = new wxMenuItem(p_ctx_menu, wxID_ANY, "Set Slider to 25");
    p_ctx_menu->Append(menu_item_3);
    auto* menu_item_4 = new wxMenuItem(p_ctx_menu, wxID_ANY, "Set Slider to 75");
    p_ctx_menu->Append(menu_item_4);
    auto* menu_item_5 = new wxMenuItem(p_ctx_menu, wxID_ANY, "Set Gauge to 25");
    p_ctx_menu->Append(menu_item_5);
    auto* menu_item_6 = new wxMenuItem(p_ctx_menu, wxID_ANY, "Set Gauge to 75");
    p_ctx_menu->Append(menu_item_6);

    ctx_menu.Bind(wxEVT_MENU,
[this](wxCommandEvent&) { m_animation_ctrl->Play(); },
    menu_item->GetId());
    ctx_menu.Bind(wxEVT_MENU,
[this](wxCommandEvent&) { m_animation_ctrl->Stop(); },
    menu_item_2->GetId());
    ctx_menu.Bind(wxEVT_MENU,
[this](wxCommandEvent&) { m_slider->SetValue(25); },
    menu_item_3->GetId());
    ctx_menu.Bind(wxEVT_MENU,
[this](wxCommandEvent&) { m_slider->SetValue(75); },
    menu_item_4->GetId());
    ctx_menu.Bind(wxEVT_MENU,
[this](wxCommandEvent&) { m_gauge->SetValue(25); },
    menu_item_5->GetId());
    ctx_menu.Bind(wxEVT_MENU,
[this](wxCommandEvent&) { m_gauge->SetValue(75); },
    menu_item_6->GetId());

    wxStaticCast(event.GetEventObject(), wxWindow)->PopupMenu(&ctx_menu);
}

namespace wxue_img
{
    // art/../art/face-smile.webp
    const unsigned char face_smile_webp[2148] {
        82,73,70,70,92,8,0,0,87,69,66,80,86,80,56,88,10,0,0,0,16,0,0,0,47,0,0,47,0,0,65,76,80,72,51,2,0,0,1,25,49,105,138,
        209,123,17,253,15,7,114,176,109,51,244,234,29,79,146,99,219,182,109,166,58,182,90,251,84,167,180,217,217,182,109,
        171,183,109,251,207,238,76,149,217,157,176,141,152,128,9,64,200,141,230,85,78,41,165,228,241,206,27,111,188,100,
        100,136,114,122,25,161,130,223,126,251,39,77,97,37,148,85,220,33,219,157,231,173,154,229,42,75,0,16,0,64,160,64,
        234,169,167,182,198,18,188,20,180,80,51,6,56,19,201,184,69,158,234,193,67,117,123,4,32,186,86,218,14,139,80,113,
        165,154,13,226,77,50,214,9,121,197,211,209,4,16,183,214,193,25,66,28,149,45,1,241,11,245,173,16,67,30,7,89,30,64,
        25,108,140,104,211,36,128,215,36,139,20,19,165,164,193,192,179,48,91,148,185,2,190,184,225,170,114,75,214,3,120,
        23,70,114,235,238,15,198,27,53,136,219,16,144,1,11,169,193,169,171,140,192,117,227,162,72,25,65,168,204,165,132,
        191,148,12,0,149,184,148,242,11,147,17,202,114,17,2,144,17,5,151,55,74,203,16,175,184,188,85,94,134,120,202,229,
        55,73,200,0,198,51,46,112,83,115,25,224,175,139,156,54,235,79,243,23,184,201,233,176,94,192,187,117,128,225,244,
        209,125,173,17,190,254,91,5,220,39,90,64,241,100,93,117,77,4,216,174,63,198,79,194,84,16,181,180,187,242,242,242,
        223,54,16,189,147,163,52,15,129,187,214,137,68,8,218,104,211,41,177,89,95,77,80,0,245,95,200,137,209,4,69,154,108,
        12,37,166,192,103,83,85,80,16,64,32,193,129,80,36,77,81,132,84,115,41,177,36,60,52,75,29,21,88,0,96,165,73,143,
        83,36,69,19,52,169,150,153,74,146,34,25,129,163,46,106,46,15,11,44,0,194,72,143,80,20,77,17,20,69,147,186,24,43,
        153,226,100,132,110,91,175,137,54,128,177,8,0,139,0,71,78,145,36,69,82,4,77,72,214,70,103,141,0,197,17,0,161,16,
        245,201,5,231,21,213,65,49,134,96,89,20,0,97,184,0,37,73,138,194,73,130,196,9,140,86,87,41,69,149,144,199,123,31,
        124,113,199,59,129,64,89,22,67,24,4,101,17,16,153,146,4,133,227,56,129,225,24,134,160,40,0,195,178,140,80,136,0,
        160,8,139,178,32,86,74,16,24,137,224,24,10,40,194,34,192,176,140,144,1,20,0,16,224,147,33,24,138,162,8,176,136,
        144,21,50,12,2,114,186,0,86,80,56,32,2,6,0,0,48,33,0,157,1,42,48,0,48,0,0,0,0,37,176,2,116,202,17,216,114,4,161,
        191,27,251,145,251,43,253,243,116,68,210,118,51,249,47,182,111,118,126,160,63,20,255,128,245,48,254,233,246,103,
        220,3,204,7,242,127,233,31,237,255,192,118,0,244,0,254,247,252,239,209,187,216,139,208,55,246,3,210,215,246,75,
        224,103,246,127,246,19,224,47,249,103,244,159,249,191,159,252,128,31,192,59,0,63,141,126,14,254,160,120,163,252,
        223,234,3,179,155,186,62,178,126,196,232,14,250,203,245,79,200,159,219,207,242,156,224,239,12,254,67,253,127,241,
        19,246,187,252,206,113,175,201,63,169,126,52,254,224,127,179,216,40,254,179,249,19,178,43,252,139,251,135,227,79,
        248,239,134,175,225,63,48,63,170,251,128,249,127,251,31,218,175,216,15,241,63,227,191,211,255,174,127,108,255,25,
        253,227,255,95,129,79,214,191,99,63,211,3,182,89,26,80,42,52,143,18,163,56,186,88,61,48,114,89,143,14,247,55,226,
        126,201,134,72,234,142,201,209,193,23,57,175,180,127,134,82,92,194,244,126,230,0,116,65,250,181,135,23,232,244,
        23,71,244,4,70,84,0,0,254,252,81,109,21,39,192,57,3,104,98,143,117,190,205,171,133,188,28,26,249,177,78,236,109,
        29,197,38,209,99,235,66,62,52,58,182,167,50,196,85,252,229,188,11,22,126,62,139,250,83,128,119,63,124,230,18,223,
        197,91,148,205,171,31,134,239,246,149,253,159,85,121,45,207,18,131,114,33,2,98,224,147,134,16,122,26,58,141,203,
        61,135,190,121,251,226,54,127,203,58,254,4,121,191,180,210,33,220,193,148,114,3,15,88,147,49,200,207,9,39,211,84,
        250,186,1,46,92,231,125,11,129,23,53,240,140,30,243,255,255,93,251,99,104,165,150,180,159,138,226,216,242,246,100,
        42,201,38,252,142,201,218,69,222,250,115,144,68,47,141,110,138,211,60,181,145,200,170,88,121,11,148,40,220,12,163,
        110,17,145,96,240,122,232,148,1,165,16,80,117,1,72,153,138,64,40,237,220,80,162,223,163,70,219,120,234,191,237,
        97,49,226,32,74,187,192,129,118,147,11,83,124,31,124,241,94,254,16,96,183,190,153,37,22,92,115,141,210,54,208,92,
        35,207,145,170,245,55,128,157,42,101,114,99,73,16,112,20,231,24,28,150,141,225,144,23,242,76,121,143,191,59,249,
        43,43,39,176,96,227,116,111,213,63,43,178,205,122,187,35,60,159,96,49,207,95,22,90,179,61,30,128,153,56,1,37,233,
        71,234,30,50,50,237,157,106,10,112,84,90,124,208,148,60,119,1,226,3,127,43,87,223,228,50,6,193,169,106,186,65,217,
        233,192,180,147,181,184,144,11,191,73,229,228,158,104,17,159,68,164,103,73,13,37,242,229,156,0,67,177,15,51,181,
        45,17,122,39,16,222,249,227,77,254,169,231,109,30,58,198,53,25,18,161,2,122,82,238,186,232,168,213,78,235,16,186,
        94,57,178,219,139,8,211,163,213,155,21,53,182,241,232,252,211,104,112,40,201,27,184,7,149,255,244,10,243,72,187,
        178,52,220,181,51,86,40,239,182,129,241,16,138,17,10,200,55,63,235,169,141,125,20,40,106,255,254,51,110,172,15,
        56,149,56,92,8,13,142,31,253,249,111,213,146,177,121,240,158,161,251,237,150,125,186,52,118,184,253,100,17,128,
        56,9,54,29,117,89,248,127,136,253,128,203,172,247,159,229,111,193,121,122,240,38,227,77,213,18,23,55,110,187,224,
        241,177,83,155,2,53,52,29,167,144,169,118,106,174,103,226,88,17,199,15,109,229,179,66,42,151,102,101,250,132,147,
        216,209,214,98,250,70,39,16,124,48,113,121,107,40,4,57,121,232,165,38,175,183,242,31,79,76,222,191,238,31,255,227,
        134,118,21,138,63,209,145,223,113,65,254,191,35,202,173,167,255,230,211,9,58,93,234,26,245,237,97,220,181,255,249,
        131,251,164,133,96,235,241,136,119,174,39,132,91,159,153,240,54,67,237,198,53,113,63,87,88,30,131,63,60,191,243,
        227,87,31,193,175,34,90,253,13,180,80,235,156,56,145,0,132,100,54,15,57,200,139,255,215,30,105,133,214,17,124,91,
        145,110,204,255,255,171,28,189,137,70,15,157,98,174,1,117,28,38,158,119,159,145,53,146,56,157,2,7,31,182,206,198,
        185,190,30,199,232,189,113,197,240,229,24,233,146,254,68,148,229,199,173,193,217,204,228,230,243,215,205,181,156,
        111,183,22,221,66,54,54,49,79,43,136,50,95,77,140,61,238,71,217,197,111,252,137,57,230,17,37,240,66,243,23,254,
        149,131,18,172,99,74,198,157,98,79,254,11,161,100,120,137,105,111,254,147,205,96,215,190,39,97,255,26,172,61,153,
        108,112,69,160,113,245,23,226,250,192,117,230,255,255,153,252,193,133,32,111,162,141,90,239,236,215,142,215,19,
        66,104,9,90,19,49,58,62,142,32,245,196,39,224,126,43,252,221,151,118,244,176,172,64,187,35,76,100,10,208,219,79,
        54,98,154,172,157,65,151,29,88,182,142,255,62,74,214,118,124,142,103,39,157,167,35,238,68,125,90,110,12,93,17,50,
        247,36,62,148,135,46,1,251,110,128,1,227,41,153,235,52,17,233,234,255,208,135,79,91,116,158,198,198,211,110,151,
        173,134,225,167,247,245,74,239,32,68,78,164,47,105,186,45,90,135,30,132,244,95,215,202,250,15,164,199,58,177,20,
        100,227,158,175,71,211,206,119,241,103,202,54,34,177,21,204,167,41,48,165,108,118,58,182,109,235,251,178,107,112,
        98,203,241,40,61,203,223,158,102,27,17,159,157,148,42,215,244,119,71,122,67,65,242,201,223,116,23,28,63,250,236,
        3,62,199,68,209,227,152,209,24,215,188,238,19,229,201,30,117,213,101,111,94,10,178,199,137,246,251,94,4,154,12,
        78,159,232,246,116,146,152,129,110,4,97,110,42,117,94,3,233,28,248,251,55,121,13,183,187,224,29,127,42,144,173,
        194,147,155,193,224,65,14,120,225,182,94,89,97,105,119,165,89,123,65,225,219,73,140,184,78,59,161,207,221,127,16,
        127,215,46,13,215,179,243,252,234,224,238,163,52,42,192,72,166,119,218,19,241,169,241,150,183,70,98,95,194,78,228,
        58,13,60,152,22,243,252,135,196,139,208,110,44,242,30,105,240,240,167,51,97,196,177,204,192,109,133,173,70,37,195,
        195,147,251,14,150,154,23,255,168,122,41,31,192,154,48,94,50,123,208,255,255,75,191,200,110,52,246,22,204,210,235,
        228,190,142,195,241,68,126,166,77,129,252,61,43,213,216,145,5,254,254,64,58,68,158,114,8,9,252,189,249,215,187,
        211,202,4,254,83,168,8,215,9,28,166,70,69,250,58,109,250,128,196,32,0
    };

    }

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************

/////////////////// Non-generated Copyright/License Info ////////////////////
// Purpose:   Common controls dialog
// Author:    Ralph Walden
// Copyright: Copyright (c) 2020-2025 KeyWorks Software (Ralph Walden)
// License:   Apache License -- see ../../LICENSE
/////////////////////////////////////////////////////////////////////////////

#include <wx/artprov.h>

#include "mainframe.h"  // auto-generated: ../wxui_generated/mainframe_base.h and ../wxui_generated/mainframe_base.cpp

void MainFrame::OnCommonDialog(wxCommandEvent& WXUNUSED(event))
{
    CommonCtrls dlg(this);
    dlg.ShowModal();
}

void CommonCtrls::OnInit(wxInitDialogEvent& event)
{
    wxSize menu_size = { 16, 16 };
    m_bmpComboBox->Append("Home", wxArtProvider::GetBitmap(wxART_GO_HOME, wxART_MENU));
    m_bmpComboBox->Append("Print", wxArtProvider::GetBitmap(wxART_PRINT, wxART_MENU, menu_size));

    event.Skip();  // transfer all validator data to their windows and update UI
}

CommonCtrls::~CommonCtrls()
{
    delete m_popup_win;
}

void CommonCtrls::OnListChecked(wxCommandEvent& WXUNUSED(event))
{
    m_infoBar->ShowMessage("wxEVT_CHECKLISTBOX event");
    Fit();
}

void CommonCtrls::OnRadioBox(wxCommandEvent& WXUNUSED(event))
{
    m_infoBar->ShowMessage("wxEVT_RADIOBOX event");
    Fit();
}

void CommonCtrls::OnSlider(wxCommandEvent& WXUNUSED(event))
{
    m_infoBar->ShowMessage("wxEVT_SLIDER event");
    Fit();
}

void CommonCtrls::OnListBox(wxCommandEvent& WXUNUSED(event))
{
    m_infoBar->ShowMessage("wxEVT_LISTBOX event");
    Fit();
}

void CommonCtrls::OnCheckBox(wxCommandEvent& WXUNUSED(event))
{
    // TODO: Implement OnCheckBox
}

void CommonCtrls::OnChoice(wxCommandEvent& WXUNUSED(event))
{
    // TODO: Implement OnChoice
}

void CommonCtrls::OnRadio(wxCommandEvent& WXUNUSED(event))
{
    // TODO: Implement OnRadio
}

void CommonCtrls::OnPopupBtn(wxCommandEvent& event)
{
    if (m_popup_win)
        delete m_popup_win;
    m_popup_win = new PopupWin(this);

    auto btn = wxStaticCast(event.GetEventObject(), wxWindow);
    auto pos = btn->ClientToScreen(wxPoint(0, 0));
    m_popup_win->Position(pos, btn->GetSize());

    m_popup_win->Popup();
}
