# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wxue_generated_code

    # Non-base classes
    ${CMAKE_CURRENT_LIST_DIR}/bitmaps_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/booktest_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/commonctrls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/data_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/images.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mainframe.cpp
    ${CMAKE_CURRENT_LIST_DIR}/popupwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/propsheet_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/python_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/testformpanel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wizard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wxue_data.cpp

    # Base classes
    ${CMAKE_CURRENT_LIST_DIR}/dlgissue_956.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dlgissue_960.cpp
    ${CMAKE_CURRENT_LIST_DIR}/form_aui_toolbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/form_menu_bar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/form_popup_menu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/form_ribbonbar_gallery.cpp
    ${CMAKE_CURRENT_LIST_DIR}/form_ribbonbar_tool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/form_toolbar_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/maintestdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tools_dlg.cpp

)

set (wxue_generated_code_data

    ${CMAKE_CURRENT_LIST_DIR}/../xrc/python_dlg.xrc

)
